spring.application.name=task-tracker-backend
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/tasktracker
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT configuration
app.jwt.secret=DOUdGHStTsURDTOIx4YaELMBs2g8e36huFKTPf2z9jx
app.jwt.expiration-ms=86400000

